import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * AI知识库侧边栏配置
 * 动态显示当前选中的分类
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🧠 AI基础与原理',
      link: {type: 'doc', id: 'ai-basics/index'},
      collapsed: false,
      items: [
        {type: 'doc', id: 'ai-basics/what-is-ai', label: '01. 什么是AI？'},
        {type: 'doc', id: 'ai-basics/ai-terms', label: '02. AI常见术语词典'},
      ],
    },
    {
      type: 'category',
      label: '🛠️ AI工具与应用',
      link: {type: 'doc', id: 'ai-tools/index'},
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '聊天对话类',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-tools/chatgpt-guide', label: '01. ChatGPT使用指南'},
            {type: 'doc', id: 'ai-tools/claude-guide', label: '02. Claude使用指南'},
            {type: 'doc', id: 'ai-tools/domestic-chat-tools', label: '03. 国内AI对话工具对比'},
          ],
        },
        {
          type: 'category',
          label: '图像创作类',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-tools/ai-image-tools', label: '01. AI绘画工具推荐'},
            {type: 'doc', id: 'ai-tools/ai-photo-edit', label: '02. AI修图工具'},
            {type: 'doc', id: 'ai-tools/ai-avatar', label: '03. AI头像生成'},
          ],
        },
        {
          type: 'category',
          label: '办公效率类',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-tools/ai-office-tools', label: '01. AI办公工具推荐'},
            {type: 'doc', id: 'ai-tools/ai-meeting', label: '02. AI会议助手'},
            {type: 'doc', id: 'ai-tools/ai-document', label: '03. AI文档处理'},
          ],
        },
        {
          type: 'category',
          label: '编程辅助类',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-tools/ai-coding', label: '01. AI编程助手'},
            {type: 'doc', id: 'ai-tools/code-debug', label: '02. 代码解释与调试'},
          ],
        },
        {
          type: 'category',
          label: '视频音频类',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-tools/ai-video', label: '01. AI视频工具'},
            {type: 'doc', id: 'ai-tools/ai-audio', label: '02. AI音频工具'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '💻 AI开发实践',
      link: {type: 'doc', id: 'ai-dev/index'},
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '提示词工程',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-dev/prompt-basics', label: '01. 提示词基础'},
            {type: 'doc', id: 'ai-dev/prompt-frameworks', label: '02. 提示词框架'},
            {type: 'doc', id: 'ai-dev/role-prompting', label: '03. 角色提示技巧'},
            {type: 'doc', id: 'ai-dev/few-shot-prompting', label: '04. 少样本提示'},
          ],
        },
        {
          type: 'category',
          label: '实战案例',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-dev/weekly-report', label: '01. 用AI写周报'},
            {type: 'doc', id: 'ai-dev/ai-ppt', label: '02. 用AI做PPT'},
            {type: 'doc', id: 'ai-dev/learning-assistant', label: '03. 用AI整理笔记'},
            {type: 'doc', id: 'ai-dev/ai-data-analysis', label: '04. 用AI分析数据'},
          ],
        },
        {
          type: 'category',
          label: '应用开发入门',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-dev/ai-app-roadmap', label: '01. AI应用开发路线'},
            {type: 'doc', id: 'ai-dev/api-basics', label: '02. API调用基础'},
            {type: 'doc', id: 'ai-dev/low-code-ai', label: '03. 低代码AI应用'},
            {type: 'doc', id: 'ai-dev/dify-tutorial', label: '04. Dify入门教程'},
          ],
        },
        {
          type: 'category',
          label: '进阶实践',
          collapsed: true,
          items: [
            {type: 'doc', id: 'ai-dev/rag-tutorial', label: '01. RAG系统搭建'},
            {type: 'doc', id: 'ai-dev/agent-dev', label: '02. AI Agent开发'},
            {type: 'doc', id: 'ai-dev/fine-tuning-basics', label: '03. 模型微调入门'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🏭 AI行业应用',
      link: {type: 'doc', id: 'ai-industry/index'},
      collapsed: false,
      items: [
        {type: 'doc', id: 'ai-industry/ai-education', label: '01. AI辅助教学'},
        {type: 'doc', id: 'ai-industry/ai-homework', label: '02. AI作业批改'},
        {type: 'doc', id: 'ai-industry/ai-language-learning', label: '03. 语言学习AI'},
        {type: 'doc', id: 'ai-industry/ai-medical', label: '04. AI医疗诊断'},
        {type: 'doc', id: 'ai-industry/ai-health', label: '05. AI健康管理'},
        {type: 'doc', id: 'ai-industry/ai-drug-discovery', label: '06. 药物研发AI'},
        {type: 'doc', id: 'ai-industry/ai-finance', label: '07. AI智能投顾'},
        {type: 'doc', id: 'ai-industry/ai-risk-control', label: '08. AI风控系统'},
        {type: 'doc', id: 'ai-industry/ai-banking-service', label: '09. 智能客服'},
        {type: 'doc', id: 'ai-industry/ai-recommendation', label: '10. AI推荐系统'},
        {type: 'doc', id: 'ai-industry/ai-ecommerce-service', label: '11. AI智能客服'},
        {type: 'doc', id: 'ai-industry/ai-content-gen', label: '12. AI内容生成'},
        {type: 'doc', id: 'ai-industry/ai-writing', label: '13. AI辅助写作'},
        {type: 'doc', id: 'ai-industry/ai-video-production', label: '14. AI视频制作'},
        {type: 'doc', id: 'ai-industry/ai-music', label: '15. AI音乐创作'},
        {type: 'doc', id: 'ai-industry/ai-hr', label: '16. AI人力资源'},
        {type: 'doc', id: 'ai-industry/ai-legal', label: '17. AI法务助手'},
        {type: 'doc', id: 'ai-industry/ai-marketing', label: '18. AI营销自动化'},
        {type: 'doc', id: 'ai-industry/ai-quality', label: '19. AI质量检测'},
        {type: 'doc', id: 'ai-industry/ai-supply-chain', label: '20. AI供应链优化'},
      ],
    },
    {
      type: 'category',
      label: '📈 AI资讯与趋势',
      link: {type: 'doc', id: 'ai-news/index'},
      collapsed: false,
      items: [
        {type: 'doc', id: 'ai-news/weekly-news', label: '01. 本周AI大事'},
        {type: 'doc', id: 'ai-news/new-products', label: '02. 新产品发布'},
        {type: 'doc', id: 'ai-news/funding-news', label: '03. 融资并购动态'},
        {type: 'doc', id: 'ai-news/llm-trends', label: '04. 大模型发展趋势'},
        {type: 'doc', id: 'ai-news/multimodal-trends', label: '05. 多模态AI进展'},
        {type: 'doc', id: 'ai-news/agent-trends', label: '06. AI Agent演进'},
        {type: 'doc', id: 'ai-news/edge-ai', label: '07. 端侧AI兴起'},
        {type: 'doc', id: 'ai-news/ai-earnings', label: '08. AI公司财报解读'},
        {type: 'doc', id: 'ai-news/ai-policy', label: '09. 政策监管动态'},
        {type: 'doc', id: 'ai-news/ai-safety', label: '10. AI安全与伦理'},
        {type: 'doc', id: 'ai-news/ai-investment', label: '11. AI投资趋势'},
        {type: 'doc', id: 'ai-news/ai-talent', label: '12. AI人才市场'},
        {type: 'doc', id: 'ai-news/ai-jobs', label: '13. AI替代职业分析'},
        {type: 'doc', id: 'ai-news/review', label: '14. 2024AI发展回顾'},
        {type: 'doc', id: 'ai-news/predictions', label: '15. 2025AI趋势预测'},
      ],
    },
    {
      type: 'category',
      label: '📚 AI学习资源',
      link: {type: 'doc', id: 'ai-resources/index'},
      collapsed: false,
      items: [
        {type: 'doc', id: 'ai-resources/beginner-courses', label: '01. AI入门视频课程'},
        {type: 'doc', id: 'ai-resources/ai-books', label: '02. AI科普书籍推荐'},
        {type: 'doc', id: 'ai-resources/ai-podcasts', label: '03. AI播客推荐'},
        {type: 'doc', id: 'ai-resources/ml-courses', label: '04. 机器学习课程'},
        {type: 'doc', id: 'ai-resources/dl-tutorials', label: '05. 深度学习教程'},
        {type: 'doc', id: 'ai-resources/llm-technical', label: '06. 大模型技术详解'},
        {type: 'doc', id: 'ai-resources/open-source-projects', label: '07. 开源项目推荐'},
        {type: 'doc', id: 'ai-resources/ai-competitions', label: '08. AI竞赛平台'},
        {type: 'doc', id: 'ai-resources/datasets', label: '09. 实验数据集'},
        {type: 'doc', id: 'ai-resources/chinese-communities', label: '10. 中文AI社区'},
        {type: 'doc', id: 'ai-resources/global-communities', label: '11. 国际AI社区'},
        {type: 'doc', id: 'ai-resources/tech-blogs', label: '12. 技术博客推荐'},
        {type: 'doc', id: 'ai-resources/classic-papers', label: '13. 经典论文导读'},
        {type: 'doc', id: 'ai-resources/latest-papers', label: '14. 最新论文追踪'},
        {type: 'doc', id: 'ai-resources/industry-reports', label: '15. 行业研究报告'},
        {type: 'doc', id: 'ai-resources/online-platforms', label: '16. 在线实验平台'},
        {type: 'doc', id: 'ai-resources/model-zoos', label: '17. 模型仓库'},
        {type: 'doc', id: 'ai-resources/dev-tools', label: '18. 开发工具推荐'},
      ],
    },
    {
      type: 'category',
      label: '🦞 OpenClaw',
      link: {type: 'doc', id: 'openclaw/index'},
      collapsed: false,
      items: [
        {type: 'doc', id: 'openclaw/prerequisites', label: '01. 前置条件'},
        {type: 'doc', id: 'openclaw/install_core', label: '02. 安装核心程序'},
        {type: 'doc', id: 'openclaw/install_terminal', label: '03. 安装交互式终端'},
        {type: 'doc', id: 'openclaw/verify_installation', label: '04. 验证安装'},
        {type: 'doc', id: 'openclaw/personality_config', label: '05. 人格设定'},
        {type: 'doc', id: 'openclaw/memory_system', label: '06. 记忆系统'},
        {type: 'doc', id: 'openclaw/short_term_memory', label: '07. 短期记忆'},
        {type: 'doc', id: 'openclaw/channels_overview', label: '08. 渠道概览'},
        {type: 'doc', id: 'openclaw/setup_telegram', label: '09. Telegram配置'},
        {type: 'doc', id: 'openclaw/setup_other_channels', label: '10. 其他渠道'},
        {type: 'doc', id: 'openclaw/setup_llm', label: '11. LLM模型配置'},
        {type: 'doc', id: 'openclaw/setup_skills', label: '12. 技能配置'},
        {type: 'doc', id: 'openclaw/recommended_skills', label: '13. 推荐技能'},
        {type: 'doc', id: 'openclaw/multi_agent_system', label: '14. 多Agent系统'},
        {type: 'doc', id: 'openclaw/team_setup', label: '15. 团队配置'},
        {type: 'doc', id: 'openclaw/tutorials', label: '16. 实用教程'},
      ],
    },
  ],
};

export default sidebars;
